name: 'GPT Translate TEST'
description: 'Markdown translation into any other language powered by ChatGPT'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  apikey:
    description: 'OpenAI API Key'
    required: true
  languages:
    desecription: 'Languages'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'globe'
  color: 'green'
